### ISSUE TITLE
Can´t drag easy images on certain sites like twitter or reddit

### ISSUE THREAD

**Issue by Droarm** [lcandy2/Select-like-a-Boss#2]
Hello i love this extension for a long time but the last update broke a little. 

When i try to drag a image the extension does not allow it and I have to try several times (twice) to achieve it. this is problematic when you use with other extensions to save images fast as: [im gentle man](https://chrome.google.com/webstore/detail/im-a-gentleman/afjaicccalbbickikgdegaihmajaidpd) that allows you to save images as it was done before in opera: only dragging them.

The problem is on twitter, reddit and other sites.

Example: https://www.reddit.com/r/memes/

Hope you can solve, thank you.

**Comment by lcandy2** [comment]
Thanks for opening an issue. I just reviewed the code and noticed I forget to consider the type what you dragged.

I’ll fix that as soon as possible 🤍

**Comment by lcandy2** [comment]
Just resolved the issue in the version 2022 May and submitted to the store, expected to be reviewing until tomorrow.
