### ISSUE TITLE
Text Quote function on many forums and websites not working

### ISSUE THREAD

**Issue by Matr0x** [lcandy2/Select-like-a-Boss#5]
Works like a charm, but unfortunately conflicts with text Quote function on many forums and websites making it unusable (as the older version too 2015.4.24). It would be great to fix this annoyance. Overclockers . ru for example

Cent Browser 5.0.1002.182 (Chromium 102.0.5005.167)

Thank you a lot for this awesome extension. Best regards !

**Comment by lcandy2** [comment]
Hey, I just uploaded a new version, please check if it is compatible with the site you mentioned. I checked the site you mentioned, but I don't really understand how the quote function you mentioned works, if the problem still exists, feel free to reply.
