### ISSUE TITLE
Conflicts with Imagus Mod on google images site

### ISSUE THREAD

**Issue by bottleblue** [lcandy2/Select-like-a-Boss#6]
I know this is a very specific use case but there's a conflict with Imagus Mod extension with Select-like-a-Boss on Google Images. Hovering over the images will make it seem like you're holding down the mouse button and highlighting everything when you move your mouse.  

How to recreate:
Install Imagus Mod
https://addons.mozilla.org/en-US/firefox/addon/imagus-mod/

Search for something on Google Images. Hover over an image till it enlarges then move your mouse around. It will act like it's being held down and everything gets highlighted.

Happens on Chrome and Firefox but I'm using Select-Like-a-Boss for Chrome. There's no alternative link text copier for Chrome like there is for Firefox which doesn't require holding down a modifier key.

**Comment by lcandy2** [comment]
Fixed in the latest version.

**Comment by bottleblue** [comment]
Not fixed for me. It's still happening
